greenery:

  outputs:
    dbt_zkan:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_zkan

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_sun_bigquery:
      type: bigquery
      method: service-account
      project: turing-chess-434208-a6
      dataset: dbt_sun
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/turing-chess-434208-a6-skooldio-deb4-bigquery-dbt-659e2e7e26d9.json
      location: asia-southeast1

    prod_bigquery:
      type: bigquery
      method: service-account
      project: dataengineercafe
      dataset: deb_bootcamp
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/YOUR-KEYFILE.json
      location: asia-southeast1

  target: dbt_sun_bigquery