greenery:

  outputs:
    dbt_zkan:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_zkan

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_liffy_bigquery:
      type: bigquery
      method: service-account
      project: crafty-hook-437603-h2
      dataset: dbt_liffy
      threads: 1
      keyfile: dbt_greenery.json
      location: asia-southeast1

    prod_bigquery:
      type: bigquery
      method: service-account
      project: crafty-hook-437603-h2
      dataset: deb_bootcamp
      threads: 1
      keyfile: dbt_greenery.json
      location: asia-southeast1

  target: dbt_liffy_bigquery