[tool.poetry]
name = "play-with-poetry"
version = "0.1.0"
description = ""
authors = ["Prachya Kusumamarn <91284127+sunpcy@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
